:encoding: utf-8
:imagesdir: img
:cpp: C++

== Optimization of functions solving differential equations

This tutorial discusses the example: https://github.com/dietmarwo/fast-cma-es/blob/master/examples/f8.py[f8.py], an implementation of the F-8 aircraft control problem https://mintoc.de/index.php/F-8_aircraft[F-8_aircraft] which aims at controlling an aircraft in a time-optimal way from an initial state to a terminal state.

It provides the information you need for your own optimization projects involving differential equations in the
context of parallel retries. The example is described in detail in 
http://www.midaco-solver.com/data/pub/The_Oracle_Penalty_Method.pdf[Oracle Penalty]: In 8 hours on a PC
with 2 GHz clock rate and 2 GB RAM working memory - back in 2010 - the equality constraints could not 
completely be solved using the oracle penalty method. We will use a fixed penalty weight instead.

=== How to implement differential equations in Python

Integrating differential equations inside the objective function is costly. We should do everything we can
to speed things up. Scipy provides two interfaces https://docs.scipy.org/doc/scipy/reference/generated/scipy.integrate.ode.html[ode] 
and https://docs.scipy.org/doc/scipy/reference/generated/scipy.integrate.solve_ivp.html[solve_ivp]. 
We provide an `ode` based implementation for comparison but recommend to use compiled ODEs based on 
the https://github.com/AnyarInc/Ascent[Ascent] library, see
https://github.com/dietmarwo/fast-cma-es/blob/master/_fcmaescpp/ascent.cpp[ascent.cpp]
Using this you see a good solution in less than a second on a fast 16 core machine. 
