:encoding: utf-8
:imagesdir: img
:cpp: C++

== Solving the GTOPX Benchmark Problems using PYGMO2/PAGMO2

fcmaes performs really well for the very hard http://www.midaco-solver.com/data/pub/GTOPX_Benchmarks.pdf[GTOPX benchmarks]
as shown in the https://github.com/dietmarwo/fast-cma-es/blob/master/README.adoc[README]. 
Here we want to analyze what part of the library is responsible, 
the specific implementation of the basic algorithms (DE -> CMA) or the coordinated retry meta algorithm. 
To check this we replace the fcmaes versions of DE and CMA by the ones provided by 
https://github.com/esa/pygmo2[pygmo2] / https://github.com/esa/pagmo2[pagmo2]. 
It seems it is mostly the meta algorithm, as the results are very similar.

=== Performance of the PYGMO2/PAGMO2 optimization algorithms
Install pygmo (`pip install pygmo`) and
execute https://github.com/dietmarwo/fast-cma-es/blob/master/examples/benchmark_gtop_pygmo.py[benchmark_gtop_pygmo.py]
to reproduce the results. The same optimization algorithm
was applied for all problems, using the same parameters both for the optimization algorithm and the coordinated retry.
The solution times given in the tables below are for Linux / AMD 3950x CPU. 

.GTOP coordinated retry results for stopVal = 1.005*absolute_best
[width="80%",cols="3,^2,^2,^2,^2,^2,^2",options="header"]
|=========================================================
|problem |runs | absolute best |stopVal |success rate |mean time|sdev time
|Cassini1 |100 |4.9307 |4.95535 |100% |4.37s |2.37s
|Cassini2 |100 |8.383 |8.42491 |100% |54.26s |21.24s
|Gtoc1 |100 |-1581950 |-1574079.60199 |100% |19.12s |12.18s
|Messenger |100 |8.6299 |8.67305 |100% |23.71s |10.59s
|Rosetta |100 |1.3433 |1.35002 |100% |56.91s |18.66s
|Tandem |100 |-1500.46 |-1492.99502 |60% |860.95s |394.26s
|Sagas |100 |18.188 |18.27894 |100% |5.29s |1.97s
|=========================================================

Note that 'stopVal' is the value determining success and 'mean time' includes the time for failed runs.
Note that these results are preliminary - a 15% slower CPU was used and we did less meta algorithm runs,
we will replace these soon by more accurate numbers and will add results for Messenger Full.

The results prove that https://github.com/esa/pygmo2[pygmo2] provides
excellent optimization algorithms sufficient to solve the  
http://www.midaco-solver.com/data/pub/GTOPX_Benchmarks.pdf[GTOPX benchmarks].

=== Challenge
Can you reproduce these results without using fcmaes relying on the https://github.com/esa/pygmo2[pygmo2]
https://esa.github.io/pygmo2/archipelago.html[parallelization mechanisms]?
