# Copyright (c) Dietmar Wolz.
#
# This source code is licensed under the MIT license found in the
# LICENSE file in the root directory.

__version__ = '1.5.1'

__all__ = [
    'advexamples'
    'benchmark_gtop'
    'benchmark_gtop_pygmo'
    'cassini_minlp'
    'cassini2_minlp'
    'clustering'
    'crypto'
    'elitecass2'
    'examples'
    'f8'
    'filter'
    'gear_train'
    'harvesting'
    'house'
    'interferometry'
    'interferometry_udp'
    'jobshop'
    'lotka'
    'moexamples'
    'noisy_tsp'
    'powerplant'
    'quant'
    'reproblem'
    'repython'
    'robot'
    'routing'
    'rover'
    'scheduling'
    'siemens'
    'solo_mgar'
    'solo_mgar_udp'
    'spring'
    'subset'
    'subset_mo'
    'tandem_minlp'
    'top_trumps'
    'tutorial'
    'vaccination'
    'vessel'
    'vilar'
]
