def phase1_build_info() -> dict: ...
def _phase1_probe_sum(values) -> float: ...
def optimize_acma(fun, batch_fun, guess, lower, upper, sigma, *, seed: int,
                  runid: int = 0, max_evaluations: int = 100000,
                  stop_fitness: float = ..., stop_hist: float = -1.0,
                  mu: int = 0, popsize: int = 31, accuracy: float = 1.0,
                  normalize: bool = True, delayed_update: bool = True,
                  update_gap: int = -1, workers: int = 1): ...
def optimize_bite(fun, guess, lower, upper, *, seed: int, runid: int = 0,
                  max_evaluations: int = 100000,
                  stop_fitness: float = ...,
                  M: int = 1, popsize: int = 0,
                  stall_criterion: int = 0): ...
def optimize_crfmnes(batch_fun, guess, lower, upper, sigma: float = 0.3, *,
                     seed: int, runid: int = 0,
                     max_evaluations: int = 100000,
                     stop_fitness: float = ...,
                     popsize: int = 32,
                     penalty_coef: float = 1e5,
                     use_constraint_violation: bool = True,
                     normalize: bool = False): ...
def optimize_da(fun, guess, lower, upper, *, seed: int, runid: int = 0,
                max_evaluations: int = 100000,
                use_local_search: bool = True): ...
def optimize_de(fun, dim: int, lower, upper, guess, sigma, ints, *, seed: int,
                runid: int = 0, max_evaluations: int = 100000,
                keep: float = 200.0, stop_fitness: float = ...,
                popsize: int = 31, F: float = 0.5, CR: float = 0.9,
                min_sigma: float = 0.0, min_mutate: float = 0.1,
                max_mutate: float = 0.5, workers: int = 1,
                terminate=None): ...
def optimize_pgpe(batch_fun, guess, lower, upper, sigma, *, seed: int,
                  runid: int = 0, max_evaluations: int = 100000,
                  stop_fitness: float = ..., popsize: int = 32,
                  lr_decay_steps: int = 1000, use_ranking: bool = True,
                  center_learning_rate: float = 0.15,
                  stdev_learning_rate: float = 0.1,
                  stdev_max_change: float = 0.2, b1: float = 0.9,
                  b2: float = 0.999, eps: float = 1e-8,
                  decay_coef: float = 1.0, normalize: bool = True): ...
def gtop_gtoc1(x) -> float: ...
def gtop_cassini1(x) -> float: ...
def gtop_messenger(x) -> float: ...
def gtop_messengerfull(x) -> float: ...
def gtop_cassini2(x) -> float: ...
def gtop_rosetta(x) -> float: ...
def gtop_sagas(x) -> float: ...
def gtop_tandem(x, sequence) -> float: ...
def gtop_tandem_unconstrained(x, sequence) -> float: ...
def gtop_cassini1_minlp(x) -> tuple[float, float]: ...
def gtop_cassini2_minlp(x) -> float: ...

class ACMA:
    dim: int
    popsize: int
    stop: int
    def __init__(self, guess, lower, upper, sigma, *,
                 max_evaluations: int = 100000,
                 stop_fitness: float = ..., stop_hist: float = -1.0,
                 mu: int = 0, popsize: int = 31, accuracy: float = 1.0,
                 seed: int, runid: int = 0, normalize: bool = True,
                 delayed_update: bool = True, update_gap: int = -1): ...
    def ask(self): ...
    def tell(self, ys): ...
    def tell_x(self, ys, xs): ...
    def population(self): ...
    def result(self): ...

class CRFMNES:
    dim: int
    popsize: int
    def __init__(self, guess, lower, upper, sigma: float = 0.3,
                 popsize: int = 32, *, seed: int, runid: int = 0,
                 penalty_coef: float = 1e5,
                 use_constraint_violation: bool = True,
                 normalize: bool = False): ...
    def ask(self): ...
    def tell(self, ys): ...
    def population(self): ...
    def result(self): ...

class DE:
    dim: int
    popsize: int
    stop: int
    def __init__(self, dim: int, lower, upper, guess, sigma, ints,
                 popsize: int = 31, keep: float = 200.0, F: float = 0.5,
                 CR: float = 0.9, min_sigma: float = 0.0,
                 min_mutate: float = 0.1, max_mutate: float = 0.5, *,
                 seed: int, runid: int = 0): ...
    def ask(self): ...
    def tell(self, ys): ...
    def population(self): ...
    def result(self): ...

class PGPE:
    dim: int
    popsize: int
    def __init__(self, guess, lower, upper, sigma, popsize: int = 32, *,
                 seed: int, runid: int = 0, lr_decay_steps: int = 1000,
                 use_ranking: bool = False,
                 center_learning_rate: float = 0.15,
                 stdev_learning_rate: float = 0.1,
                 stdev_max_change: float = 0.2, b1: float = 0.9,
                 b2: float = 0.999, eps: float = 1e-8,
                 decay_coef: float = 1.0, normalize: bool = True): ...
    def ask(self): ...
    def tell(self, ys): ...
    def population(self): ...
    def result(self): ...

class MODE:
    dim: int
    nobj: int
    ncon: int
    popsize: int
    stop: int
    def __init__(self, dim: int, nobj: int, ncon: int,
                 lower, upper, ints, popsize: int = 64,
                 F: float = 0.5, CR: float = 0.9,
                 pro_c: float = 0.5, dis_c: float = 15.0,
                 pro_m: float = 0.9, dis_m: float = 20.0,
                 nsga_update: bool = True, pareto_update: float = 0.0,
                 min_mutate: float = 0.1, max_mutate: float = 0.5, *,
                 seed: int, runid: int = 0): ...
    def ask(self): ...
    def tell(self, ys): ...
    def tell_switch(self, ys, nsga_update: bool = True,
                    pareto_update: float = 0.0): ...
    def set_population(self, xs, ys): ...
    def population(self): ...
